### ISSUE TITLE
incorrect number of blocks shown

### ISSUE THREAD

**Issue by sethlloydcollins** [mumblebaj/MMM-EskomSePush#1]
On the display bar, each segment represents 30 mins, but have noticed the last segment also is shown in orange, despite it not being scheduled for load shedding. IE: If load shedding is scheduled for 6:00 - 8:30, then the blocks for 6:00 until 8:30 are shown as orange, but also the 8:30 - 9:00 block shows in orange.

**Comment by mumblebaj** [comment]
Thanks @sethlloydcollins for picking this up. Issue has been fixed and new version pushed.

**Comment by mumblebaj** [comment]
Done
