### ISSUE TITLE
Enhancement Request: No Loadshedding

### ISSUE THREAD

**Issue by ConfuciusZA** [mumblebaj/MMM-EskomSePush#10]
It would be great if you can include an option to hide bar/header/both when loadshedding has been suspended (or no loadshedding is happening). 

Perhaps something like
noLoadSheddingVisibility
with options of "Bars", "Header", "Both" which will hide the specified section when loadshedding is suspended.

**Comment by mumblebaj** [comment]
Hi. You are more than welcome to fork the module and make the changes and submit a PR if you would like the functionality.

**Comment by mumblebaj** [comment]
Hiding those elements does not remove them from the page, they will still continue to occupy space. Removing them completely would be a lot more work. If I may ask, why would you want to hide any of it?

**Comment by ConfuciusZA** [comment]
Merely personal preference. Not a space issue for me.

**Comment by mumblebaj** [comment]
I have found an easy way. Will add an option for `hideElements`. You can set it to "both" and it will hide everything if there is no loadshedding. If there is loadshedding it should display as normal.

**Comment by mumblebaj** [comment]
Update has been made and pushed. You can update and add the option to the config of the module.

![image](https://github.com/mumblebaj/MMM-EskomSePush/assets/39963138/975ae7d1-23cc-4968-aaab-b802ffac71a7)

**Comment by ConfuciusZA** [comment]
Awesome, thanks. I just started to play around in the code hiding all elements when events == No upcoming loadshedding and the option is true. Probably not the most efficient, but i expect it'll work.

**Comment by mumblebaj** [comment]
Rather update the module and use the option I provided. It is easier. Will also avoid issues updating in future.

**Comment by ConfuciusZA** [comment]
Already done that. Thanks!! You're a legend.

**Comment by ConfuciusZA** [comment]
Works like a charm
