### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by ConfuciusZA** [mumblebaj/MMM-EskomSePush#8]
Hi

I'm running this on a monitor (1080p) turned 90' and your module isn't aligned properly. 
I have removed/reinstalled without luck. 
Regardless of where I place this module (top bar, middle_center etc) it's always out of alignment. 
No other modules are displaying in this way. 
Example attached.
Any ideas? 
![cropped](https://github.com/mumblebaj/MMM-EskomSePush/assets/94459054/a28890fb-f1eb-4212-9759-e716665df824)

**Comment by mumblebaj** [comment]
Hi. Made some changes and it should align a little better.

![image](https://github.com/mumblebaj/MMM-EskomSePush/assets/39963138/31fda53b-44ad-4089-944e-bd330a15cc35)

Let me know if this works better for you.

**Comment by ConfuciusZA** [comment]
Perfect, thank you so much!
