### ISSUE TITLE
Test Flag

### ISSUE THREAD

**Issue by ConfuciusZA** [mumblebaj/MMM-EskomSePush#9]
I've been looking at your code, best i can, trying to find the "test" flag. 
According to the ESP API documentation a "?test" parameter can be used in the area parameter to avoid quota issues when debugging. 
Could you perhaps include that as a config option?

**Comment by mumblebaj** [comment]
The test data returned does not fit with the module setup. The starting times does not fit with the starting times of the actual production times and the module does not cater for that. Too much changes required to cater for those time sets.

**Comment by ConfuciusZA** [comment]
No worries. Thanks for the feedback.
